<app-skl-form 
	formtitle="{{'${componentname$}title'|translate}}" 
	[formcolnames]="queryitems" 
	(action)="getquery($event)" 	
	[ncolcount]=${colcount$}   
	[formdata]="querydata" 
	[buttons]="[{'name':'reset','icon':'reload'},{'name':'search','icon':'search'}]"
	(formdatachange)="formdatachange($event)">
</app-skl-form>
